spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT CONFIG (REQUIRED)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# OAuth2 redirect after login
app.oauth2.authorized-redirect-uri=http://localhost:8080/auth/success

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

springdoc.api-docs.path=/api-docs

# Debug white label errors
#.
server.error.include-message=always
server.error.include-binding-errors=always
